### PR TITLE
Added czech layout

### PR DESCRIPTION
**Pull request by tortillax**
I needed Czech layout, so why not share it with community. Optimized for Linux, characters "`" and "~" won't work on Windows.

### CODE REVIEW

**Comment by mame82** [comment]
Thanks @tortillax ... Before merging, could you please check if adding in an SHIFT+ALT modifier to keyboard props allows sending tilde like done here https://github.com/hak5darren/USB-Rubber-Ducky/pull/25/files

**Comment by tortillax** [comment]
SHIFT + ALT switches keyboard layouts for me, which I believe is default bahaviour on Windows. In the file you linked, tilde is bound to _right alt + tilde_, which doesnt output nothing for me (windows, czech layout).

In file uploaded by me, there is tilde bound to _right alt + A_, which works for czech layout on linux systems (line 102). On windows with czech layout, you can output it with _right alt + 1_ (comment right above).

I havent found any way how to output tilde with same keys on both systems, so only solution that comes to mind is either changing properties file, or generating **cs.windows.properties** and **cs.linux.properties**.

**Comment by mame82** [comment]
>   or generating cs.windows.properties and cs.linux.properties

This would be a valid Approach, the command line language argument ends up here:
https://github.com/mame82/duckencoder.py/blob/master/duckencoder.py#L407

Which means `-l cs.windows` or `-l cs.linux` could be used as command line argument.

Anyway, I think this is a corner case and thus merge your current PR (although in fact I'm not able to test it).

So thanks for contribution and extending this. I'll carry it over to `P4wnP1` RePo on next Major commit (which will take some time, as I'm currently discussing low level HID communication and restarted the third time to improve performance ... won't commit before this is done)

If I may I ask: Are you using duckencoder.py stand-alone or with P4wnP1 ?

**Comment by tortillax** [comment]
Right now I am using it in combination with your [duck2spark](https://github.com/mame82/duck2spark).

P4wnP1 looks really good, and I am looking forward using it when I get hands on Respberry Pi Zero.

**Pull request merged**
